# Generated by Django 3.1.7 on 2021-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Email_id', models.EmailField(max_length=15)),
                ('phone_number', models.IntegerField()),
                ('Address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
